### ISSUE TITLE
pm_asephonons fails when xyz and pbc=true

### ISSUE THREAD

**Issue by patrick-austin** [muon-spectroscopy-computational-project/muon-galaxy-tools#113]
Description
-----------
As a result of fixing the default value for pbc to be true (see #112 ), the test that runs with an xyz file fails. Presumably this is because it doesn't have any lattice vectors and so `pbc` are meaningless.

In the inputs, we explicitly request a `.cell` file:
https://github.com/muon-spectroscopy-computational-project/muon-galaxy-tools/blob/6a07c4caed5ef35f35198d54ebafd7d1d6d60edb/pm_asephonons/pm_asephonons.xml#L51

However I can't see a similar restriction in PyMuonSuite itself. Furthermore, we are running tests with other types of file, `cif`, `extxyz` and `xyz`. Having played with the UI, it seems that while only cell files will be picked up automatically, I can manually upload and set an `xyz` file and submit.

Proposed Changes
-------------------
Either:

1. Remove the tests with other file types, and stick with the message that only cell files are allowed
2. Relax the message and allow the file extensions that we test for, and add in a validator that ensures we cannot submit xyz and pbc at the same time

I don't know if it's also worth change PyMuonSuite to handle this early, e.g. here:
https://github.com/muon-spectroscopy-computational-project/pymuon-suite/blob/3aaab2de4b24f40f8361950117e03b5ca6a9637c/pymuonsuite/quantum/__main__.py#L113-L118
Perhaps we could only set if the atoms object has lattice vectors, otherwise we can throw early?

**Comment by elichad** [comment]
This is a known issue in pymuonsuite: https://github.com/muon-spectroscopy-computational-project/pymuon-suite/issues/50 . We probably could do with something to catch this, it's a problem for multiple tools.
We have some tests using `expect_failure` because of this same issue: https://github.com/muon-spectroscopy-computational-project/muon-galaxy-tools/blob/e5b6b4e110ac8df4f2698ece6cf80f33c881d5b2/pm_symmetry/pm_symmetry.xml#L51-L56

For this issue I'd vote for option 2, since cif and extxyz do work as you've noticed.
