### ISSUE TITLE
[pm_yaml_config] supercell help and type inconsistent

### ISSUE THREAD

**Issue by patrick-austin** [muon-spectroscopy-computational-project/muon-galaxy-tools#87]
Currently, the help for the `param` says "This can either be a single int, a list of three integers or a 3x3 matrix of integers". However the `type ="integer"`, so attempting to input a list of integers (or anything that's not a single integer) will fail to submit.

Either:
- [ ] Remove the help text that references the list/matrix options. Downside is it would be more restrictive.
- [ ] Change the type to be "text" like `k_points_grid` below it. Downside is you could submit anything as text, I could say the supercell was "zebra" if I really wanted (this is already the case for `k_points_grid`.
- [x] Use a regex [validator](https://docs.galaxyproject.org/en/latest/dev/schema.html#validators-for-textual-inputs-text-select) to allow free text, but only if it matches our regex. This might be the best solution, but I don't know if we can construct a check that matches integers OR lists of 3 integers OR matrix of 3*3 integers.

I don't know how valuable the ability to specify an arbitrary supercell matrix is here, so not sure what's best.

**Comment by bgruening** [comment]
Galaxy offers you some validations build-in.

https://docs.galaxyproject.org/en/latest/dev/schema.html#validators-for-textual-inputs-text-select

So you could check if it's only numbers and whitespaces and a new line character.

**Comment by elichad** [comment]
Good catch. The `field` param in `muspinsim_config` is similar to this and uses a text field, but the validation there is contained within the muspinsim package rather than the Galaxy tool because it's more complex (allows variables and functions and such). In this case using the built in text validation option that @bgruening suggests is probably the way to go. You definitely _could_ write a regex to catch any of multiple formats, but I don't know that it's worth it
