### ISSUE TITLE
Consider combining pm_yaml_config and pm_muairss_write

### ISSUE THREAD

**Issue by anish-mudaraddi** [muon-spectroscopy-computational-project/muon-galaxy-tools#99]
pm_muairss_write tool is currently written to use an external file for setting config parameters. 

the tool pm_yaml_config is used to write this file. It also  sets parameters for the UEP and read stages,

If we wanted to combine these tools – we'd have to think about whether it'd be best to put all the options in pm_muairss_write or split them up and put them in their relevant tools. 

We'll need to identify parameters used for multiple stages and how to handle them

**Comment by elichad** [comment]
Adding to this: parameters like `uep_chden` don't make sense within a purely Galaxy-based workflow. They only come into play if someone wants to take their config and use it outside Galaxy. This is confusing.

> the label is suboptimal, it took me a while to work out exactly what we were doing with this input and why it was "Only required for use outside Muon Galaxy".

**Comment by patrick-austin** [comment]
A possible approach to this would be to maintain a config only tool (to generate re-usable config files), and expand the "actual" tools to have the option of either reading a full config file or alternatively, interactively specifying only the relevant config settings.

In order to prevent duplication of code in this case, we could attempt refactor sections of the current config file into macros. These would then all be imported by the config tool to maintain its current functionality. The "actual" tools could then import only the macros that are relevant to their operation, and only shows these interactive options when a full config file is not provided.

This would be a more complex approach then simply refactoring directly into the main tool. However the advantage would be allowing macros to be shared between tools without duplicating code (i.e. any parameters which are relevant to multiple tools only need their xml to be defined once). It also gives the user two modes of operation (re-usable config file or interactive), however it may not be that likely that a user will want to define the config file for external use.

The following seems to be the most useful in documenting how to use macros for this purpose:
https://planemo.readthedocs.io/en/latest/writing_advanced.html#macros-reusable-elements
there are also examples here:
https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/config/sample/job_conf.xml.sample_advanced

**Comment by patrick-austin** [comment]
Another motivation for actioning this is it would prevent situations where we ask the user if their config file contains certain values (if `pm_muairss_write` had an interactive interface, we could directly check the variable):
https://github.com/muon-spectroscopy-computational-project/muon-galaxy-tools/blob/6a07c4caed5ef35f35198d54ebafd7d1d6d60edb/pm_muairss_write/pm_muairss_write.xml#L61

**Comment by patrick-austin** [comment]
Also consider using the https://docs.galaxyproject.org/en/latest/dev/schema.html#tool-configfiles-configfile tag to simplify the `printf` statements in our command.
